program DFend;

uses
  Forms,
  MainUnit in 'MainUnit.pas' {DFendReloadedMainForm},
  CommonComponents in 'CommonComponents.pas',
  CommonTools in 'CommonTools.pas',
  PrgSetupUnit in 'PrgSetupUnit.pas',
  SetupDosBoxFormUnit in 'SetupDosBoxFormUnit.pas' {SetupDosBoxForm},
  LanguageSetupUnit in 'LanguageSetupUnit.pas',
  PrgConsts in 'PrgConsts.pas',
  VistaToolsUnit in 'VistaToolsUnit.pas',
  GameDBUnit in 'GameDBUnit.pas',
  GameDBToolsUnit in 'GameDBToolsUnit.pas',
  ProfileEditorFormUnit in 'ProfileEditorFormUnit.pas' {ProfileEditorForm},
  SetupFormUnit in 'SetupFormUnit.pas' {SetupForm},
  IconManagerFormUnit in 'IconManagerFormUnit.pas' {IconManagerForm},
  ProfileMountEditorFormUnit in 'ProfileMountEditorFormUnit.pas' {ProfileMountEditorForm},
  DosBoxUnit in 'DosBoxUnit.pas',
  HistoryFormUnit in 'HistoryFormUnit.pas' {HistoryForm},
  TemplateFormUnit in 'TemplateFormUnit.pas' {TemplateForm},
  UninstallFormUnit in 'UninstallFormUnit.pas' {UninstallForm},
  UninstallSelectFormUnit in 'UninstallSelectFormUnit.pas' {UninstallSelectForm},
  pngimage in 'pngimage\pngimage.pas',
  ViewImageFormUnit in 'ViewImageFormUnit.pas' {ViewImageForm},
  CreateConfFormUnit in 'CreateConfFormUnit.pas' {CreateConfForm},
  TemplateSelectProfileFormUnit in 'TemplateSelectProfileFormUnit.pas' {TemplateSelectProfileForm},
  WizardFormUnit in 'WizardFormUnit.pas' {WizardForm},
  CreateShortcutFormUnit in 'CreateShortcutFormUnit.pas' {CreateShortcutForm},
  DiskImageToolsUnit in 'DiskImageToolsUnit.pas',
  CreateImageUnit in 'CreateImageUnit.pas' {CreateImageForm},
  InfoFormUnit in 'InfoFormUnit.pas' {InfoForm},
  TransferFormUnit in 'TransferFormUnit.pas' {TransferForm},
  BuildInstallerFormUnit in 'BuildInstallerFormUnit.pas' {BuildInstallerForm},
  ProgressFormUnit in 'ProgressFormUnit.pas' {ProgressForm},
  ResHookUnit in 'ResHookUnit.pas',
  SerialEditFormUnit in 'SerialEditFormUnit.pas' {SerialEditForm},
  ChangeProfilesFormUnit in 'ChangeProfilesFormUnit.pas' {ChangeProfilesForm},
  BuildInstallerForSingleGameFormUnit in 'BuildInstallerForSingleGameFormUnit.pas' {BuildInstallerForSingleGameForm},
  UserInfoFormUnit in 'UserInfoFormUnit.pas' {UserInfoForm},
  ModernProfileEditorFormUnit in 'ModernProfileEditorFormUnit.pas' {ModernProfileEditorForm},
  ModernProfileEditorBaseFrameUnit in 'ModernProfileEditorBaseFrameUnit.pas' {ModernProfileEditorBaseFrame: TFrame},
  ModernProfileEditorGameInfoFrameUnit in 'ModernProfileEditorGameInfoFrameUnit.pas' {ModernProfileEditorGameInfoFrame: TFrame},
  ModernProfileEditorDirectoryFrameUnit in 'ModernProfileEditorDirectoryFrameUnit.pas' {ModernProfileEditorDirectoryFrame: TFrame},
  ModernProfileEditorDOSBoxFrameUnit in 'ModernProfileEditorDOSBoxFrameUnit.pas' {ModernProfileEditorDOSBoxFrame: TFrame},
  ModernProfileEditorHardwareFrameUnit in 'ModernProfileEditorHardwareFrameUnit.pas' {ModernProfileEditorHardwareFrame: TFrame},
  ModernProfileEditorCPUFrameUnit in 'ModernProfileEditorCPUFrameUnit.pas' {ModernProfileEditorCPUFrame: TFrame},
  ModernProfileEditorMemoryFrameUnit in 'ModernProfileEditorMemoryFrameUnit.pas' {ModernProfileEditorMemoryFrame: TFrame},
  ModernProfileEditorGraphicsFrameUnit in 'ModernProfileEditorGraphicsFrameUnit.pas' {ModernProfileEditorGraphicsFrame: TFrame},
  ListViewImageUnit in 'ListViewImageUnit.pas',
  ModernProfileEditorKeyboardFrameUnit in 'ModernProfileEditorKeyboardFrameUnit.pas' {ModernProfileEditorKeyboardFrame: TFrame},
  StatisticsFormUnit in 'StatisticsFormUnit.pas' {StatisticsForm},
  ModernProfileEditorSoundFrameUnit in 'ModernProfileEditorSoundFrameUnit.pas' {ModernProfileEditorSoundFrame: TFrame},
  ModernProfileEditorSoundBlasterFrameUnit in 'ModernProfileEditorSoundBlasterFrameUnit.pas' {ModernProfileEditorSoundBlasterFrame: TFrame},
  ModernProfileEditorGUSFrameUnit in 'ModernProfileEditorGUSFrameUnit.pas' {ModernProfileEditorGUSFrame: TFrame},
  ModernProfileEditorMIDIFrameUnit in 'ModernProfileEditorMIDIFrameUnit.pas' {ModernProfileEditorMIDIFrame: TFrame},
  ModernProfileEditorJoystickFrameUnit in 'ModernProfileEditorJoystickFrameUnit.pas' {ModernProfileEditorJoystickFrame: TFrame},
  ModernProfileEditorDrivesFrameUnit in 'ModernProfileEditorDrivesFrameUnit.pas' {ModernProfileEditorDrivesFrame: TFrame},
  ModernProfileEditorSerialPortsFrameUnit in 'ModernProfileEditorSerialPortsFrameUnit.pas' {ModernProfileEditorSerialPortsFrame: TFrame},
  ModernProfileEditorSerialPortFrameUnit in 'ModernProfileEditorSerialPortFrameUnit.pas' {ModernProfileEditorSerialPortFrame: TFrame},
  ModernProfileEditorNetworkFrameUnit in 'ModernProfileEditorNetworkFrameUnit.pas' {ModernProfileEditorNetworkFrame: TFrame},
  ModernProfileEditorDOSEnvironmentFrameUnit in 'ModernProfileEditorDOSEnvironmentFrameUnit.pas' {ModernProfileEditorDOSEnvironmentFrame: TFrame},
  ModernProfileEditorStartFrameUnit in 'ModernProfileEditorStartFrameUnit.pas' {ModernProfileEditorStartFrame: TFrame},
  CacheChooseFormUnit in 'CacheChooseFormUnit.pas' {CacheChooseForm},
  ModernProfileEditorMouseFrameUnit in 'ModernProfileEditorMouseFrameUnit.pas' {ModernProfileEditorMouseFrame: TFrame},
  ModernProfileEditorVolumeFrameUnit in 'ModernProfileEditorVolumeFrameUnit.pas' {ModernProfileEditorVolumeFrame: TFrame},
  IconLoaderUnit in 'IconLoaderUnit.pas',
  LanguageEditorStartFormUnit in 'LanguageEditorStartFormUnit.pas' {LanguageEditorStartForm},
  LanguageEditorFormUnit in 'LanguageEditorFormUnit.pas' {LanguageEditorForm},
  PlaySoundFormUnit in 'PlaySoundFormUnit.pas' {PlaySoundForm};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'D-Fend Reloaded';
  Application.CreateForm(TDFendReloadedMainForm, DFendReloadedMainForm);
  Application.Run;
end.
